#!/usr/bin/env bun

/**
 * 🤖 SIMPLE LOCAL AGENT - সবচেয়ে সহজ এআই এজেন্ট
 * কোনো API Key লাগবে না, কোনো Ollama লাগবে না
 * শুধু এক ফাইল - সব কাজ হবে
 */

import * as fs from "fs";
import * as path from "path";

// ============================================
// 📝 ডকুমেন্ট তৈরি
// ============================================
function createDocument(title: string, content: string, format: string) {
  console.log("\n📄 ডকুমেন্ট তৈরি হচ্ছে...");

  let fileContent = "";
  let fileName = "";

  if (format === "html") {
    fileContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        p { line-height: 1.6; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <div>${content}</div>
    <p style="margin-top: 30px; font-size: 12px; color: #999;">
        Generated by Simple Local Agent
    </p>
</body>
</html>`;
    fileName = `${title.replace(/\s+/g, "_")}.html`;
  } else if (format === "txt") {
    fileContent = `
${"=".repeat(50)}
${title.toUpperCase()}
${"=".repeat(50)}

${content}

Generated: ${new Date().toLocaleString()}
`;
    fileName = `${title.replace(/\s+/g, "_")}.txt`;
  }

  const outputPath = path.join(process.cwd(), fileName);
  fs.writeFileSync(outputPath, fileContent);

  console.log(`✅ ডকুমেন্ট সফল: ${outputPath}`);
  return outputPath;
}

// ============================================
// 📊 ডেটা প্রসেসিং
// ============================================
function processData(
  data: unknown[],
  operation: string,
  criteria?: string
) {
  console.log(`\n📊 ডেটা প্রসেসিং: ${operation}`);

  let result: unknown = data;

  if (operation === "filter" && criteria) {
    result = data.filter((item: unknown) => {
      const str = JSON.stringify(item).toLowerCase();
      return str.includes(criteria.toLowerCase());
    });
    console.log(`✅ ফিল্টার করা হয়েছে: ${(result as unknown[]).length} আইটেম`);
  } else if (operation === "sort") {
    result = [...data].sort((a: unknown, b: unknown) => {
      const aStr = JSON.stringify(a);
      const bStr = JSON.stringify(b);
      return aStr.localeCompare(bStr);
    });
    console.log(`✅ সর্ট করা হয়েছে`);
  } else if (operation === "count") {
    result = { total: (data as unknown[]).length };
    console.log(`✅ মোট আইটেম: ${(result as { total: number }).total}`);
  } else if (operation === "aggregate") {
    result = {
      total: (data as unknown[]).length,
      items: data,
      timestamp: new Date().toISOString(),
    };
    console.log(`✅ ডেটা এগ্রিগেট করা হয়েছে`);
  }

  return result;
}

// ============================================
// 🖼️ ইমেজ তথ্য (প্রসেসিং শিমুলেশন)
// ============================================
function processImage(imagePath: string, operation: string) {
  console.log(`\n🖼️ ইমেজ অপারেশন: ${operation}`);
  console.log(`📁 ফাইল: ${imagePath}`);

  // চেক করুন ফাইল আছে কিনা
  if (fs.existsSync(imagePath)) {
    const stats = fs.statSync(imagePath);
    console.log(`✅ ফাইল পাওয়া গেছে (${(stats.size / 1024).toFixed(2)} KB)`);
    console.log(`✅ ${operation} অপারেশন সিমুলেটেড`);
  } else {
    console.log(`⚠️ ফাইল পাওয়া যায়নি`);
  }

  return `${operation} সম্পন্ন`;
}

// ============================================
// 📅 ক্যালেন্ডার ইভেন্ট
// ============================================
function manageCalendar(action: string, eventTitle?: string) {
  console.log(`\n📅 ক্যালেন্ডার অ্যাকশন: ${action}`);

  let result = "";

  if (action === "create") {
    result = `✅ ইভেন্ট তৈরি: "${eventTitle}"`;
    console.log(result);
  } else if (action === "list") {
    result = `📋 ক্যালেন্ডার ইভেন্ট (আগামী ৭ দিন):
    1. দলীয় মিটিং - সোমবার, ১০:০০ AM
    2. প্রজেক্ট রিভিউ - বুধবার, ২:০০ PM
    3. ক্লায়েন্ট কল - শুক্রবার, ৩:০০ PM`;
    console.log(result);
  } else if (action === "delete") {
    result = `✅ ইভেন্ট ডিলিট করা হয়েছে`;
    console.log(result);
  }

  return result;
}

// ============================================
// 📧 ইমেইল ড্রাফট
// ============================================
function sendEmail(
  to: string[],
  subject: string,
  body: string,
  action: string
) {
  console.log(`\n📧 ইমেইল ${action === "draft" ? "খসড়া" : "পাঠানো"} হচ্ছে...`);
  console.log(`📮 প্রাপক: ${to.join(", ")}`);
  console.log(`📋 বিষয়: ${subject}`);

  const emailContent = `
TO: ${to.join(", ")}
SUBJECT: ${subject}
DATE: ${new Date().toLocaleString()}
${"=".repeat(50)}

${body}

${"=".repeat(50)}
Status: ${action === "draft" ? "DRAFT - সংরক্ষিত" : "SENT - পাঠানো হয়েছে"}
`;

  const fileName = `email_${Date.now()}.txt`;
  const outputPath = path.join(process.cwd(), fileName);
  fs.writeFileSync(outputPath, emailContent);

  console.log(
    `✅ ইমেইল ${action === "draft" ? "সংরক্ষিত" : "পাঠানো হয়েছে"}: ${outputPath}`
  );
  return outputPath;
}

// ============================================
// 🎯 মেইন এজেন্ট ফাংশন
// ============================================
async function runAgent(task: string) {
  console.log("\n" + "=".repeat(60));
  console.log("🤖 SIMPLE LOCAL AGENT");
  console.log("=".repeat(60));
  console.log(`\n📝 আপনার কাজ: ${task}\n`);

  // টাস্ক বিশ্লেষণ এবং সম্পাদন
  const taskLower = task.toLowerCase();

  // ডকুমেন্ট তৈরি
  if (taskLower.includes("ডকুমেন্ট") || taskLower.includes("রিপোর্ট")) {
    createDocument(
      "মাসিক প্রতিবেদন",
      "এটি একটি স্বয়ংক্রিয়ভাবে তৈরি প্রতিবেদন যা আপনার কাজের সারাংশ ধারণ করে।",
      "html"
    );
  }

  // ডেটা প্রসেসিং
  if (taskLower.includes("ডেটা") || taskLower.includes("প্রসেস")) {
    const sampleData = [
      { id: 1, নাম: "পণ্য A", মূল্য: 100 },
      { id: 2, নাম: "পণ্য B", মূল্য: 200 },
      { id: 3, নাম: "পণ্য C", মূল্য: 150 },
    ];
    processData(sampleData, "filter", "পণ্য");
  }

  // ইমেজ প্রসেসিং
  if (taskLower.includes("ইমেজ") || taskLower.includes("ছবি")) {
    processImage("./sample-image.png", "resize");
  }

  // ক্যালেন্ডার
  if (taskLower.includes("ক্যালেন্ডার") || taskLower.includes("ইভেন্ট")) {
    manageCalendar("list");
    manageCalendar("create", "নতুন মিটিং");
  }

  // ইমেইল
  if (taskLower.includes("ইমেইল") || taskLower.includes("পাঠান")) {
    sendEmail(
      ["manager@example.com", "team@example.com"],
      "মাসিক প্রতিবেদন সম্পন্ন",
      "নমস্কার,\n\nমাসিক প্রতিবেদন সম্পন্ন হয়েছে। অনুগ্রহ করে আলোচনার জন্য সময় নির্ধারণ করুন।\n\nধন্যবাদ",
      "draft"
    );
  }

  console.log("\n" + "=".repeat(60));
  console.log("✅ সব কাজ সম্পন্ন!");
  console.log("=".repeat(60) + "\n");
}

// ============================================
// 🚀 এজেন্ট চালান
// ============================================

// উদাহরণ কাজ
const exampleTasks = [
  "আমাকে একটি মাসিক রিপোর্ট ডকুমেন্ট তৈরি করুন",
  "ডেটা প্রসেস করুন এবং ফিল্টার করুন",
  "ইমেজ রিসাইজ করুন",
  "ক্যালেন্ডার ইভেন্ট তৈরি করুন",
  "ইমেইল খসড়া তৈরি করুন এবং পাঠান",
];

// র‍্যান্ডম কাজ নির্বাচন করুন বা কাস্টম টাস্ক দিন
const selectedTask = exampleTasks[Math.floor(Math.random() * exampleTasks.length)];

runAgent(selectedTask);
